// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CodeCatalystAuthSchemeResolverParameters: ClientRuntime.AuthSchemeResolverParameters {
    public let operation: String
}

public protocol CodeCatalystAuthSchemeResolver: ClientRuntime.AuthSchemeResolver {
    // Intentionally empty.
    // This is the parent protocol that all auth scheme resolver implementations of
    // the service CodeCatalyst must conform to.
}

public struct DefaultCodeCatalystAuthSchemeResolver: CodeCatalystAuthSchemeResolver {
    public typealias Parameters = CodeCatalystAuthSchemeResolverParameters

    public func resolveAuthScheme(params: Parameters) throws -> [AuthOption] {
        var validAuthOptions = Array<AuthOption>()
        switch params.operation {
            default:
                validAuthOptions.append(AuthOption(schemeID: "smithy.api#httpBearerAuth"))
        }
        return validAuthOptions
    }

    public func constructParameters(context: HttpContext) throws -> Parameters {
        guard let opName = context.getOperation() else {
            throw ClientError.dataNotFound("Operation name not configured in middleware context for auth scheme resolver params construction.")
        }
        return CodeCatalystAuthSchemeResolverParameters(operation: opName)
    }
}
